name: Release Builds

on: push

env:
  QT_VERSION: "v6.3.0"

jobs:
  win64-msvc:
    name: Windows 64-bit MSVC
    runs-on: windows-2022
    env:
      INSTALL_PREFIX: 'C:\smelibs.x64'
      OS: "win64-msvc"
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.0
      - name: Build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*

  win32-msvc:
    name: Windows 32-bit MSVC
    runs-on: windows-2022
    env:
      INSTALL_PREFIX: 'C:\smelibs.x86'
      OS: "win32-msvc"
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
          toolset: 14.0
      - name: Build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*

  release:
    needs: [win64-msvc, win32-msvc]
    runs-on: ubuntu-20.04
    # upload binaries to github release if commit is tagged
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: binaries
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
